-- v1 content seed (spec-013)
--
-- Inserts the 10 official scenes and 10 official companions defined in
-- docs/product/content.md (Aurelia City). All fields except `art_url`
-- are populated; art_url stays NULL until the art pipeline catches up.
--
-- Idempotent: uses INSERT OR REPLACE so re-running the migration restores
-- canonical content without leaving stale rows behind. User-created
-- companions (source='user') are untouched.

-- ============================================================
-- scenes
-- ============================================================
INSERT OR REPLACE INTO scenes
  (id, name, mood, tags, possible_events, default_companions, unlock_condition, art_url, display_order, is_active, created_at)
VALUES
  ('pier_coffee_shop',
   'Pier Coffee Shop',
   'A small, warmly lit coffee shop at the end of the pier. Late afternoon sun streams through the windows, casting long golden shadows. The hiss of the espresso machine and the smell of fresh pastries fill the air. Always quiet enough to talk, never empty.',
   '["cafe","waterfront"]',
   '["daily_encounter","invitation","gift"]',
   '["maya","theo"]',
   NULL,
   NULL,
   1, 1, unixepoch() * 1000),

  ('sky_office',
   'Sky Office',
   'The 27th floor of an open-plan office. Floor-to-ceiling windows, hum of conversation, the constant rustle of keyboards. Late-week energy: a mix of deadlines and casual banter.',
   '["office","day"]',
   '["daily_encounter","conflict","invitation"]',
   '["ryan","aiko"]',
   NULL,
   NULL,
   2, 1, unixepoch() * 1000),

  ('twin_pines_park',
   'Twin Pines Park',
   'A wide central park bordered by twin rows of pine trees. Joggers in the morning, families in the afternoon, soft golden light in the evening. The sound of distant traffic mixes with birdsong.',
   '["park","outdoor"]',
   '["daily_encounter","invitation","milestone"]',
   '["ethan","iris"]',
   NULL,
   NULL,
   3, 1, unixepoch() * 1000),

  ('moon_bar',
   'Moon Bar',
   'A dimly lit cocktail bar on a backstreet, with neon moon decor and warm wooden counters. Soft jazz plays in the background. Quiet enough for real conversation, busy enough not to feel alone.',
   '["bar","night"]',
   '["daily_encounter","confession","gift"]',
   '["lila"]',
   NULL,
   NULL,
   4, 1, unixepoch() * 1000),

  ('sunrise_apartment',
   'Sunrise Apartment',
   'Your apartment building, mostly the shared landing or your own front door. Mornings bring the smell of fresh bread from downstairs. Quiet, familiar, the closest thing to home.',
   '["home","intimate"]',
   '["daily_encounter","gift","milestone"]',
   '["iris"]',
   NULL,
   NULL,
   5, 1, unixepoch() * 1000),

  ('brookside_bookshop',
   'Brookside Bookshop',
   'A two-floor old bookshop tucked beside a small stream. The smell of paper and dust. Reading nooks scattered between the shelves. On rainy days, the windows fog up and the shop feels like a secret.',
   '["indoor","quiet"]',
   '["daily_encounter","gift","invitation"]',
   '["sora","aiko","theo"]',
   NULL,
   NULL,
   6, 1, unixepoch() * 1000),

  ('skyline_rooftop',
   'Skyline Rooftop',
   'A rooftop garden on a residential tower. City lights stretch to the horizon. Cool wind, distant traffic hum. A place people come to think, to escape, or to be honest.',
   '["outdoor","night"]',
   '["confession","milestone","invitation"]',
   '["sora","marcus"]',
   '{"type":"min_relationship","companion_id":"sora","dim":"closeness","value":30}',
   NULL,
   7, 1, unixepoch() * 1000),

  ('iron_forge_gym',
   'Iron Forge Gym',
   'An old-school gym with iron weights, the smell of chalk and rubber. Early-morning regulars: each on their own routine, occasional nods of recognition.',
   '["indoor","energetic"]',
   '["daily_encounter","invitation"]',
   '["ethan"]',
   NULL,
   NULL,
   8, 1, unixepoch() * 1000),

  ('crescent_library',
   'Crescent Library',
   'A grand old library with high vaulted ceilings and reading rooms shaped like a crescent. Whispered conversations, the soft scratch of pens. A place for serious study or unexpected encounters.',
   '["indoor","quiet"]',
   '["daily_encounter","gift","invitation"]',
   '["marcus","aiko"]',
   NULL,
   NULL,
   9, 1, unixepoch() * 1000),

  ('harbor_market',
   'Harbor Market',
   'A weekend market along the harbor: stalls of street food, vintage trinkets, art prints. Crowded but lively. The smell of grilled fish and fresh bread.',
   '["outdoor","daytime"]',
   '["daily_encounter","gift","invitation"]',
   '["jordan","lila"]',
   NULL,
   NULL,
   10, 1, unixepoch() * 1000);

-- ============================================================
-- companions (official)
-- ============================================================
INSERT OR REPLACE INTO companions
  (id, source, created_by, is_active, name, appearance, personality, background, speech_style, relationship_role, preferred_scenes, art_url, initial_dims, created_at, updated_at)
VALUES
  ('maya', 'official', NULL, 1,
   'Maya Chen',
   'Asian-American, slim build, dark shoulder-length hair often tucked behind one ear, prefers oversized cardigans and sneakers. Always carries a sketchbook.',
   'Quietly observant, sensitive to detail, slightly anxious in groups, opens up one-on-one. Has strong aesthetic opinions she rarely volunteers.',
   'Freelance graphic designer who recently moved to Aurelia after a breakup in her last city. Spends most afternoons drawing in coffee shops to fight loneliness.',
   'Soft-spoken, often pauses mid-sentence, uses metaphors, asks more questions than she answers.',
   'crush',
   '["pier_coffee_shop","brookside_bookshop"]',
   NULL,
   '{"closeness":5,"trust":5,"romance":10,"friendship":5,"hostility":0,"tension":5,"distance":20}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('ryan', 'official', NULL, 1,
   'Ryan Park',
   'Korean-American, tall, athletic build, neat short hair, business casual at work but always with the same worn pair of running shoes.',
   'Logical and warm at once. Listens carefully. Tends to give advice when asked, not before. Hides a dry sense of humor behind professionalism.',
   'Senior software engineer at a fintech startup on the 27th floor. Single, focuses on running marathons and woodworking on weekends.',
   'Precise, occasionally formal, lets warmth show through small acts (remembering your coffee order) rather than words.',
   'colleague',
   '["sky_office","twin_pines_park"]',
   NULL,
   '{"closeness":10,"trust":10,"romance":0,"friendship":10,"hostility":0,"tension":0,"distance":15}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('lila', 'official', NULL, 1,
   'Lila Marchetti',
   'Italian-Brazilian, mid-length wavy auburn hair, sharp green eyes, always in dark clothes with one striking accessory.',
   'Reads people instantly, gives little away. Direct when she chooses to speak. Believes most relationships are temporary, which makes the ones she values fierce.',
   'Head bartender at Moon Bar. Moved to Aurelia ten years ago, has seen the bar from owner #1 to #3.',
   'Low, deliberate, often uses silence as response. Occasionally drops something startlingly honest.',
   'stranger',
   '["moon_bar","harbor_market"]',
   NULL,
   '{"closeness":0,"trust":0,"romance":5,"friendship":0,"hostility":0,"tension":10,"distance":40}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('ethan', 'official', NULL, 1,
   'Ethan Williams',
   'Black, tall, broad shoulders, close-cropped hair, always in athletic wear. Easy smile, expressive eyebrows.',
   'Genuine, encouraging, energy comes from helping people grow. Talks easily, listens harder than he lets on. Honest to a fault.',
   'Personal trainer at Iron Forge Gym. Former college athlete, switched careers after an injury. Loves cooking.',
   'Direct, motivational, peppered with "you got this" and gentle teasing.',
   'friend',
   '["iron_forge_gym","twin_pines_park"]',
   NULL,
   '{"closeness":10,"trust":10,"romance":0,"friendship":15,"hostility":0,"tension":0,"distance":10}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('sora', 'official', NULL, 1,
   'Sora Aizawa',
   'Japanese, androgynous presentation, layered black-and-platinum hair, often in oversized vintage clothes, multiple rings.',
   'Lives in the moment. Hates labels (including their own). Brutally honest, occasionally cryptic. Drawn to people who are honest back.',
   'Independent musician, plays small venues, releases music online. Crashes on friends'' couches as often as their own apartment.',
   'Casual, fragmented, song-lyric quality. Drops poetry into conversation without flagging it.',
   'crush',
   '["skyline_rooftop","brookside_bookshop"]',
   NULL,
   '{"closeness":0,"trust":5,"romance":10,"friendship":5,"hostility":0,"tension":5,"distance":30}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('marcus', 'official', NULL, 1,
   'Marcus Reid',
   'Mid-30s, mixed European descent, salt-and-pepper hair, always slightly underdressed for the situation. Carries a battered notebook.',
   'Patient, observant, holds opinions carefully and shares them slowly. Trusts hard-won. Has a wry sense of humor about heavy topics.',
   'Investigative journalist at a local paper. Divorced, no kids. Spends most evenings either writing or at the library.',
   'Measured, articulate, sometimes asks questions that feel like quiet challenges.',
   'friend',
   '["crescent_library","skyline_rooftop"]',
   NULL,
   '{"closeness":5,"trust":10,"romance":0,"friendship":10,"hostility":0,"tension":5,"distance":20}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('aiko', 'official', NULL, 1,
   'Aiko Tanaka',
   'Japanese, mid-length straight hair, minimalist style, always carries a hardcover notebook and a thermos of green tea.',
   'Reserved at first, sharp once she warms up. Has strong principles. Notices small kindnesses, returns them quietly.',
   'Architect at a mid-size firm. Works on Aurelia''s renovation projects. Lives alone with two cats. Reads architecture history for fun.',
   'Clear, considered, occasionally a touch formal. Surprises people with sudden warmth or dry humor.',
   'colleague',
   '["sky_office","brookside_bookshop","crescent_library"]',
   NULL,
   '{"closeness":5,"trust":5,"romance":5,"friendship":5,"hostility":0,"tension":5,"distance":25}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('jordan', 'official', NULL, 1,
   'Jordan Lopez',
   'Latino, lean, mid-length wavy hair, camera always around his neck, paint-stained jeans.',
   'Charming on the surface, guarded underneath. Lives by impulse. Believes art is in the imperfect moment. Hard to pin down.',
   'Street photographer who makes ends meet doing event work. Travels often, comes back to Aurelia when he runs out of money.',
   'Quick, playful, peppered with deflection. Becomes uncharacteristically still when something matters.',
   'stranger',
   '["harbor_market","moon_bar"]',
   NULL,
   '{"closeness":0,"trust":0,"romance":10,"friendship":0,"hostility":0,"tension":5,"distance":40}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('iris', 'official', NULL, 1,
   'Iris Bennett',
   'British, mid-30s, curly brown hair often tied up, comfortable practical clothes, kind eyes.',
   'Warm without being naive. Practical, generous with time, holds firm boundaries when needed. Has lived enough to be unflappable.',
   'Your neighbor across the hall. Single mom to a 7-year-old. Works as a pediatric nurse. Always has tea ready.',
   'Warm, slightly maternal, but never condescending. Occasionally sharp wit.',
   'neighbor',
   '["sunrise_apartment","twin_pines_park"]',
   NULL,
   '{"closeness":15,"trust":15,"romance":0,"friendship":15,"hostility":0,"tension":0,"distance":5}',
   unixepoch() * 1000, unixepoch() * 1000),

  ('theo', 'official', NULL, 1,
   'Theo Nakamura',
   'Japanese-Canadian, gentle features, longer side-swept hair, soft clothes, almost always in an apron at work.',
   'Gentle, attentive, listens like he''s reading a book. Quietly creative, writes short stories on the side. Slow to share, deep when he does.',
   'Barista at Pier Coffee Shop, six years running. Studied literature, never quite finished. Writes most mornings.',
   'Soft, thoughtful, occasionally quotes books in casual conversation. Smiles more than he speaks.',
   'crush',
   '["pier_coffee_shop","brookside_bookshop"]',
   NULL,
   '{"closeness":5,"trust":10,"romance":10,"friendship":10,"hostility":0,"tension":0,"distance":15}',
   unixepoch() * 1000, unixepoch() * 1000);
