-- Life Sim v1 schema (worktree A: feat/life-core)
--
-- Adds the persistence layer for AI daily-life simulation gameplay:
--   companion_daily_states  -> global rule-field cache (companion x date x slot)
--   companion_daily_flavor  -> per-user lazy flavor_text cache
--   activity_contexts       -> 6 activity types (check_in/hang_out/invite/date/gift/repair)
--   memories                -> relationship-milestone album (Free 20 / Pro unlimited)
--   push_tokens             -> mobile push registration
--   users (+timezone, +push_enabled)

-- ============================================================
-- users: timezone (IANA) + push global toggle
-- ============================================================
ALTER TABLE users ADD COLUMN timezone TEXT;
ALTER TABLE users ADD COLUMN push_enabled INTEGER NOT NULL DEFAULT 1;

-- ============================================================
-- companion_daily_states (global per-companion daily snapshot)
--
-- These fields are deterministic from (companion_id, date_local, time_slot) so
-- all users see the same "where is Maya right now". Generated by rule engine,
-- never touches an LLM. flavor_text is stored separately (per-user, lazy).
-- ============================================================
CREATE TABLE companion_daily_states (
  companion_id    TEXT NOT NULL REFERENCES companions(id),
  date_local      TEXT NOT NULL,
  time_slot       TEXT NOT NULL,
  scene_id        TEXT NOT NULL REFERENCES scenes(id),
  mood            TEXT NOT NULL,
  availability    TEXT NOT NULL,
  activity_hint   TEXT NOT NULL,
  created_at      INTEGER NOT NULL,
  PRIMARY KEY (companion_id, date_local, time_slot)
);

CREATE INDEX idx_companion_daily_states_date ON companion_daily_states(date_local);

-- ============================================================
-- companion_daily_flavor (per-user lazy LLM-generated flavor text)
--
-- Populated on demand when a user opens companion detail. Cached for the
-- (user, companion, date, slot) tuple so re-opening doesn't re-bill the LLM.
-- System task, does NOT consume user message quota.
-- ============================================================
CREATE TABLE companion_daily_flavor (
  user_id        TEXT NOT NULL REFERENCES users(id),
  companion_id   TEXT NOT NULL REFERENCES companions(id),
  date_local     TEXT NOT NULL,
  time_slot      TEXT NOT NULL,
  flavor_text    TEXT NOT NULL,
  created_at     INTEGER NOT NULL,
  PRIMARY KEY (user_id, companion_id, date_local, time_slot)
);

-- ============================================================
-- activity_contexts (6 activity types lifecycle)
--
-- daily_state_snapshot stores the JSON of mood/availability/activity_hint at
-- creation time so completion/cancel/chat-injection sees a stable snapshot
-- even if the slot ticks over mid-session.
-- ============================================================
CREATE TABLE activity_contexts (
  id                    TEXT PRIMARY KEY,
  user_id               TEXT NOT NULL REFERENCES users(id),
  companion_id          TEXT NOT NULL REFERENCES companions(id),
  scene_id              TEXT NOT NULL REFERENCES scenes(id),
  activity_type         TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'active',
  daily_state_snapshot  TEXT NOT NULL,
  started_at            INTEGER NOT NULL,
  completed_at          INTEGER,
  canceled_at           INTEGER
);

CREATE INDEX idx_activities_user_companion ON activity_contexts(user_id, companion_id, started_at);
CREATE INDEX idx_activities_status ON activity_contexts(user_id, status);

-- ============================================================
-- memories (relationship-milestone album)
--
-- memory_type is the high-level category (first_meeting / first_hangout /
-- first_date / gift_received / confession / repair / anniversary).
-- memory_subtype carries variant info that allows multiple rows for the same
-- type without duplication (e.g. anniversary 30d/100d/365d, gift_received per
-- activity_id). For singleton milestones (first_meeting etc) subtype is ''
-- (empty string) and the app enforces dedup before insert.
--
-- summary is LLM-generated (task: memory_summary) but does NOT consume user
-- message quota — it's a system task.
-- ============================================================
CREATE TABLE memories (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id),
  companion_id        TEXT NOT NULL REFERENCES companions(id),
  memory_type         TEXT NOT NULL,
  memory_subtype      TEXT NOT NULL DEFAULT '',
  scene_id            TEXT REFERENCES scenes(id),
  activity_id         TEXT REFERENCES activity_contexts(id),
  title               TEXT NOT NULL,
  summary             TEXT NOT NULL,
  key_choice          TEXT,
  relationship_delta  TEXT,
  cg_template         TEXT,
  cg_url              TEXT,
  created_at          INTEGER NOT NULL
);

CREATE INDEX idx_memories_user_companion ON memories(user_id, companion_id, created_at);
CREATE INDEX idx_memories_dedup ON memories(user_id, companion_id, memory_type, memory_subtype);

-- ============================================================
-- push_tokens (per-device registration; soft-delete via revoked_at)
-- ============================================================
CREATE TABLE push_tokens (
  user_id     TEXT NOT NULL REFERENCES users(id),
  token       TEXT NOT NULL,
  platform    TEXT NOT NULL,
  created_at  INTEGER NOT NULL,
  revoked_at  INTEGER,
  PRIMARY KEY (user_id, token)
);

CREATE INDEX idx_push_tokens_active ON push_tokens(user_id, revoked_at);
