#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    cat >&2 <<EOF
Usage: $0 <local|dev|prod> [--dry-run]

Creates derived env files from .env.local, .env.dev, or .env.prod.

Generated files:
  apps/app/.env.<env>          Expo public env values only
  infra/cloudflare/.dev.vars   Local Wrangler Worker values, local only

This script is for local development only. Use scripts/upload-worker-secrets.sh
to update Cloudflare remote Worker secrets.
EOF
    exit 1
}

target="${1:-}"
[ "$target" = "local" ] || [ "$target" = "dev" ] || [ "$target" = "prod" ] || usage
shift

dry_run=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)
            dry_run=1
            shift
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage
            ;;
    esac
done

source_file="$REPO_ROOT/.env.$target"
expo_target="$REPO_ROOT/apps/app/.env.$target"
worker_target="$REPO_ROOT/infra/cloudflare/.dev.vars"

[ -f "$source_file" ] || { echo "Env file not found: $source_file" >&2; exit 1; }

WORKER_KEYS=(
    OPENAI_API_KEY
    DEEPSEEK_API_KEY
    ARK_API_KEY
    MINIMAX_API_KEY
    MINIMAX_GROUP_ID
    MINIMAX_TTS_MODEL
    MINIMAX_TTS_VOICE_FEMALE
    MINIMAX_TTS_VOICE_MALE
    OPENAI_IMAGE_MODEL
    OPENAI_IMAGE_SIZE
    IMAGE_GEN_PROVIDER
    IMAGE_GEN_WF1_PROVIDER
    IMAGE_GEN_WF2_PROVIDER
    IMAGE_GEN_WF_CUTOUT_PROVIDER
    IMAGE_GEN_WF_OUTFIT_PROVIDER
    IMAGE_GEN_WF1_BASE_PROMPT
    IMAGE_GEN_PUBLIC_BASE_URL
    RUNNINGHUB_BASE_URL
    RUNNINGHUB_API_KEY
    RUNNINGHUB_WEBHOOK_URL
    RUNNINGHUB_WEBHOOK_SECRET
    R2_SIGNING_KEY
    AUTH_TOKEN_SECRET
    JWT_SIGNING_KEY
    APP_BASE_URL
    ALLOWED_ORIGINS
    ADMIN_EMAILS
    AUTH_SUCCESS_URL
    GOOGLE_OAUTH_CLIENT_ID
    GOOGLE_OAUTH_CLIENT_SECRET
    APPLE_SIGNIN_TEAM_ID
    APPLE_SIGNIN_KEY_ID
    APPLE_SIGNIN_CLIENT_ID
    APPLE_SIGNIN_PRIVATE_KEY
    EMAIL_PROVIDER_API_KEY
    EMAIL_FROM_ADDRESS
    STRIPE_SECRET_KEY
    STRIPE_WEBHOOK_SECRET
    STRIPE_PRICE_PRO_MONTHLY
    STRIPE_PRICE_CREDITS_SMALL
    STRIPE_PRICE_CREDITS_MEDIUM
    STRIPE_PRICE_CREDITS_LARGE
    STRIPE_SUCCESS_URL
    STRIPE_CANCEL_URL
    STRIPE_PORTAL_RETURN_URL
    STRIPE_CREDITS_SUCCESS_URL
    STRIPE_CREDITS_CANCEL_URL
    RATE_LIMIT_PER_MINUTE
    LLM_RATE_LIMIT_PER_MINUTE
    REQUEST_BODY_LIMIT_BYTES
    ASSET_UPLOAD_BODY_LIMIT_BYTES
    STRIPE_WEBHOOK_BODY_LIMIT_BYTES
)

is_worker_key() {
    local needle="$1"
    local worker_key
    for worker_key in "${WORKER_KEYS[@]}"; do
        [ "$worker_key" = "$needle" ] && return 0
    done
    return 1
}

strip_matching_quotes() {
    local value="$1"
    if [[ "$value" == \"*\" && "${value: -1}" == "\"" ]]; then
        value="${value:1:-1}"
    elif [[ "$value" == \'*\' && "${value: -1}" == "'" ]]; then
        value="${value:1:-1}"
    fi
    printf '%s' "$value"
}

write_banner() {
    local target_file="$1"
    local label="$2"
    local note="$3"
    {
        echo "# ----------------------------------------------------------------"
        echo "# AUTO-GENERATED by scripts/generate-env-files.sh - DO NOT EDIT"
        echo "# Target: $label"
    echo "# Source: .env.$target"
        echo "# Synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# $note"
        echo "# ----------------------------------------------------------------"
        echo ""
    } > "$target_file"
}

expo_tmp="$(mktemp)"
worker_tmp="$(mktemp)"
trap 'rm -f "$expo_tmp" "$worker_tmp"' EXIT

write_banner "$expo_tmp" "Expo client" "Only EXPO_PUBLIC_* keys are exposed to the Expo client bundle."
write_banner "$worker_tmp" "Cloudflare Worker local dev" "Wrangler dev reads this file locally. Do not commit it."

expo_count=0
worker_count=0

while IFS= read -r raw || [ -n "$raw" ]; do
    line="${raw#"${raw%%[![:space:]]*}"}"
    line="${line#$'\xef\xbb\xbf'}"
    case "$line" in
        ""|"#"*) continue ;;
    esac

    if [ "${line#*=}" = "$line" ]; then
        echo "Invalid line (expected KEY=value): $line" >&2
        exit 1
    fi

    key="${line%%=*}"
    value="${line#*=}"
    key="${key%"${key##*[![:space:]]}"}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    value="$(strip_matching_quotes "$value")"

    case "$key" in
        EXPO_PUBLIC_*)
            printf '%s=%s\n' "$key" "$value" >> "$expo_tmp"
            expo_count=$((expo_count + 1))
            ;;
    esac

    if [ "$target" = "local" ] && is_worker_key "$key"; then
        printf '%s=%s\n' "$key" "$value" >> "$worker_tmp"
        worker_count=$((worker_count + 1))
    fi
done < "$source_file"

echo "Preparing local env from $source_file"
echo "Expo keys: $expo_count -> $expo_target"

if [ "$target" = "local" ]; then
    echo "Worker keys: $worker_count -> $worker_target"
else
    echo "Worker keys: skipped for $target. Remote Worker secrets use scripts/upload-worker-secrets.sh $target"
fi

if [ "$dry_run" -eq 1 ]; then
    echo "Dry run complete. No files were changed."
    exit 0
fi

mkdir -p "$(dirname "$expo_target")"
mv "$expo_tmp" "$expo_target"
chmod 600 "$expo_target"

if [ "$target" = "local" ]; then
    mkdir -p "$(dirname "$worker_target")"
    mv "$worker_tmp" "$worker_target"
    chmod 600 "$worker_target"
fi

echo "Done."
