#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    cat >&2 <<EOF
Usage: $0 <dev|prod> [--dry-run]

Creates local-only derived env files from .env.dev or .env.prod.

Generated files:
  apps/app/.env.<env>          Expo public env values only
  infra/cloudflare/.dev.vars   Local Wrangler Worker values, dev only

This script is for local development only. Use scripts/sync-wrangler-secrets.sh
to update Cloudflare remote Worker secrets.
EOF
    exit 1
}

target="${1:-}"
[ "$target" = "dev" ] || [ "$target" = "prod" ] || usage
shift

dry_run=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)
            dry_run=1
            shift
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage
            ;;
    esac
done

source_file="$REPO_ROOT/.env.$target"
expo_target="$REPO_ROOT/apps/app/.env.$target"
worker_target="$REPO_ROOT/infra/cloudflare/.dev.vars"

[ -f "$source_file" ] || { echo "Env file not found: $source_file" >&2; exit 1; }

WORKER_KEYS=(
    OPENAI_API_KEY
    OPENAI_MODEL
    DEEPSEEK_API_KEY
    ARK_API_KEY
    LLM_DEFAULT_ROUTE
    RUNNINGHUB_API_KEY
    RUNNINGHUB_WEBHOOK_SECRET
    R2_SIGNING_KEY
    AUTH_TOKEN_SECRET
    JWT_SIGNING_KEY
    ALLOWED_ORIGINS
    ADMIN_EMAILS
    AUTH_SUCCESS_URL
    GOOGLE_OAUTH_CLIENT_ID
    GOOGLE_OAUTH_CLIENT_SECRET
    APPLE_SIGNIN_TEAM_ID
    APPLE_SIGNIN_KEY_ID
    APPLE_SIGNIN_CLIENT_ID
    APPLE_SIGNIN_PRIVATE_KEY
    EMAIL_PROVIDER_API_KEY
    EMAIL_FROM_ADDRESS
    STRIPE_SECRET_KEY
    STRIPE_WEBHOOK_SECRET
    STRIPE_PRICE_PRO_MONTHLY
    STRIPE_PRICE_CREDITS_SMALL
    STRIPE_PRICE_CREDITS_MEDIUM
    STRIPE_PRICE_CREDITS_LARGE
    RATE_LIMIT_PER_MINUTE
    LLM_RATE_LIMIT_PER_MINUTE
    REQUEST_BODY_LIMIT_BYTES
    ASSET_UPLOAD_BODY_LIMIT_BYTES
    STRIPE_WEBHOOK_BODY_LIMIT_BYTES
)

is_worker_key() {
    local needle="$1"
    local worker_key
    for worker_key in "${WORKER_KEYS[@]}"; do
        [ "$worker_key" = "$needle" ] && return 0
    done
    return 1
}

strip_matching_quotes() {
    local value="$1"
    if [[ "$value" == \"*\" && "${value: -1}" == "\"" ]]; then
        value="${value:1:-1}"
    elif [[ "$value" == \'*\' && "${value: -1}" == "'" ]]; then
        value="${value:1:-1}"
    fi
    printf '%s' "$value"
}

write_banner() {
    local target_file="$1"
    local label="$2"
    local note="$3"
    {
        echo "# ----------------------------------------------------------------"
        echo "# AUTO-GENERATED by scripts/prepare-local-env.sh - DO NOT EDIT"
        echo "# Target: $label"
        echo "# Source: .env.$target"
        echo "# Synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# $note"
        echo "# ----------------------------------------------------------------"
        echo ""
    } > "$target_file"
}

expo_tmp="$(mktemp)"
worker_tmp="$(mktemp)"
trap 'rm -f "$expo_tmp" "$worker_tmp"' EXIT

write_banner "$expo_tmp" "Expo client" "Only EXPO_PUBLIC_* keys are exposed to the Expo client bundle."
write_banner "$worker_tmp" "Cloudflare Worker local dev" "Wrangler dev reads this file locally. Do not commit it."

expo_count=0
worker_count=0

while IFS= read -r raw || [ -n "$raw" ]; do
    line="${raw#"${raw%%[![:space:]]*}"}"
    line="${line#$'\xef\xbb\xbf'}"
    case "$line" in
        ""|"#"*) continue ;;
    esac

    if [ "${line#*=}" = "$line" ]; then
        echo "Invalid line (expected KEY=value): $line" >&2
        exit 1
    fi

    key="${line%%=*}"
    value="${line#*=}"
    key="${key%"${key##*[![:space:]]}"}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    value="$(strip_matching_quotes "$value")"

    case "$key" in
        EXPO_PUBLIC_*)
            printf '%s=%s\n' "$key" "$value" >> "$expo_tmp"
            expo_count=$((expo_count + 1))
            ;;
    esac

    if [ "$target" = "dev" ] && is_worker_key "$key"; then
        printf '%s=%s\n' "$key" "$value" >> "$worker_tmp"
        worker_count=$((worker_count + 1))
    fi
done < "$source_file"

echo "Preparing local env from $source_file"
echo "Expo keys: $expo_count -> $expo_target"

if [ "$target" = "dev" ]; then
    echo "Worker keys: $worker_count -> $worker_target"
else
    echo "Worker keys: skipped for prod. Remote prod secrets use scripts/sync-wrangler-secrets.sh prod"
fi

if [ "$dry_run" -eq 1 ]; then
    echo "Dry run complete. No files were changed."
    exit 0
fi

mkdir -p "$(dirname "$expo_target")"
mv "$expo_tmp" "$expo_target"
chmod 600 "$expo_target"

if [ "$target" = "dev" ]; then
    mkdir -p "$(dirname "$worker_target")"
    mv "$worker_tmp" "$worker_target"
    chmod 600 "$worker_target"
fi

echo "Done."
