#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const WORKER_KEYS = new Set([
    "OPENAI_API_KEY",
    "OPENAI_MODEL",
    "DEEPSEEK_API_KEY",
    "ARK_API_KEY",
    "LLM_DEFAULT_ROUTE",
    "AUTH_TOKEN_SECRET",
    "JWT_SIGNING_KEY",
    "DEV_AUTH_TOKEN_TTL_SECONDS",
    "ALLOWED_ORIGINS",
    "ADMIN_EMAILS",
    "AUTH_SUCCESS_URL",
    "GOOGLE_OAUTH_CLIENT_ID",
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "APPLE_SIGNIN_TEAM_ID",
    "APPLE_SIGNIN_KEY_ID",
    "APPLE_SIGNIN_CLIENT_ID",
    "APPLE_SIGNIN_PRIVATE_KEY",
    "EMAIL_PROVIDER_API_KEY",
    "EMAIL_FROM_ADDRESS",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET",
    "STRIPE_PRICE_PRO_MONTHLY",
    "RATE_LIMIT_PER_MINUTE",
    "LLM_RATE_LIMIT_PER_MINUTE",
    "REQUEST_BODY_LIMIT_BYTES",
    "ASSET_UPLOAD_BODY_LIMIT_BYTES",
    "STRIPE_WEBHOOK_BODY_LIMIT_BYTES",
]);

const args = process.argv.slice(2);
const envName = readArg("--env") ?? "dev";
const dryRun = args.includes("--dry-run");

if (!["dev", "prod"].includes(envName)) {
    fail(`Invalid --env: ${envName}. Must be 'dev' or 'prod'.`);
}

const sourcePath = resolve(repoRoot, `.env.${envName}`);
if (!existsSync(sourcePath)) {
    fail(
        `Source file not found: ${sourcePath}\n` +
        `Create it by copying .env.example and filling in real values.`,
    );
}

const schemaPath = resolve(repoRoot, ".env.example");
const schemaKeys = existsSync(schemaPath) ? new Set(parseEnv(readFileSync(schemaPath, "utf8")).map((e) => e.key)) : null;

const entries = parseEnv(readFileSync(sourcePath, "utf8"));
const sourceMap = new Map(entries.map((e) => [e.key, e.value]));

if (schemaKeys) {
    for (const key of sourceMap.keys()) {
        if (!schemaKeys.has(key)) {
            console.warn(`⚠️  key '${key}' is in .env.${envName} but not in .env.example schema`);
        }
    }
}

const expoEntries = entries.filter((e) => e.key.startsWith("EXPO_PUBLIC_"));
const workerEntries = entries.filter((e) => WORKER_KEYS.has(e.key));

const expoTargetPath = resolve(repoRoot, `apps/app/.env.${envName}`);
const workerTargetPath = resolve(repoRoot, "infra/cloudflare/.dev.vars");

console.log(`📦 Syncing .env.${envName} → derived files${dryRun ? " (dry-run)" : ""}`);
console.log(`   Source: ${sourcePath}`);
console.log(`   ${entries.length} keys total | ${expoEntries.length} EXPO_PUBLIC_* | ${workerEntries.length} worker keys`);
console.log("");

writeDerived({
    targetPath: expoTargetPath,
    label: "Expo client",
    sourceRel: `.env.${envName}`,
    entries: expoEntries,
    note: "Only EXPO_PUBLIC_* keys are exposed to Expo client bundle.",
    dryRun,
});

if (envName === "prod") {
    console.log("ℹ️  Skipping worker derive for prod (use 'wrangler secret put --env production' to push)");
    console.log("");
} else {
    writeDerived({
        targetPath: workerTargetPath,
        label: "Cloudflare Worker (.dev.vars)",
        sourceRel: `.env.${envName}`,
        entries: workerEntries,
        note: "Wrangler dev reads this automatically. Do not edit.",
        dryRun,
    });
}

console.log(`✅ ${dryRun ? "Would sync" : "Synced"} ${expoEntries.length + (envName === "prod" ? 0 : workerEntries.length)} keys → ${envName === "prod" ? 1 : 2} file(s)`);

function writeDerived({ targetPath, label, sourceRel, entries: rows, note, dryRun }) {
    const banner = [
        "# ────────────────────────────────────────────────────────────────",
        `# AUTO-GENERATED by scripts/sync-env.mjs — DO NOT EDIT`,
        `# Target: ${label}`,
        `# Source: ${sourceRel}`,
        `# Synced: ${new Date().toISOString()}`,
        `# ${note}`,
        "# ────────────────────────────────────────────────────────────────",
        "",
    ].join("\n");

    const body = rows.map((e) => `${e.key}=${e.value}`).join("\n") + "\n";
    const content = banner + body;

    console.log(`→ ${targetPath} (${rows.length} keys)`);
    for (const row of rows) {
        const display = row.value ? maskValue(row.value) : "(empty)";
        console.log(`    ${row.key}=${display}`);
    }

    if (!dryRun) {
        mkdirSync(dirname(targetPath), { recursive: true });
        writeFileSync(targetPath, content, { mode: 0o600 });
    }
    console.log("");
}

function parseEnv(contents) {
    return contents
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line && !line.startsWith("#"))
        .map((line) => {
            const sep = line.indexOf("=");
            if (sep <= 0) {
                fail(`Invalid line in env file (expected KEY=value): ${line}`);
            }
            return {
                key: line.slice(0, sep).trim(),
                value: line.slice(sep + 1).trim(),
            };
        });
}

function readArg(name) {
    const idx = args.findIndex((a) => a === name || a.startsWith(`${name}=`));
    if (idx < 0) return undefined;
    const arg = args[idx];
    if (arg.includes("=")) return arg.slice(arg.indexOf("=") + 1);
    return args[idx + 1];
}

function maskValue(value) {
    if (value.length <= 8) return "***";
    return `${value.slice(0, 4)}…${value.slice(-3)} (${value.length})`;
}

function fail(msg) {
    console.error(`❌ ${msg}`);
    process.exit(1);
}
